--------------------------------------------------------
--  File created - sobota-kwietnia-18-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FTP_WORKER_INSTANCE
--------------------------------------------------------

  CREATE TABLE "FTPGETWORK"."FTP_WORKER_INSTANCE" 
   (	"XX" NUMBER, 
	"NAZWA" VARCHAR2(128 BYTE), 
	"FUNKCJA" VARCHAR2(128 BYTE) DEFAULT 'ustalic', 
	"KTO_ODPOWIADA" VARCHAR2(64 BYTE) DEFAULT 'ustalic', 
	"EMAIL2ADM" VARCHAR2(64 BYTE) DEFAULT 'ustalic', 
	"USUNIETA" NUMBER(1,0), 
	 CONSTRAINT "PK_FTP_WORKER_INSTANCE" PRIMARY KEY ("XX") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  ORGANIZATION INDEX NOCOMPRESS PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 PCTTHRESHOLD 50 INCLUDING "USUNIETA" OVERFLOW
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_FTP_WORKER_INSTANCE
--------------------------------------------------------

  CREATE UNIQUE INDEX "FTPGETWORK"."PK_FTP_WORKER_INSTANCE" ON "FTPGETWORK"."FTP_WORKER_INSTANCE" ("XX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table FTP_WORKER_INSTANCE
--------------------------------------------------------

  ALTER TABLE "FTPGETWORK"."FTP_WORKER_INSTANCE" MODIFY ("XX" NOT NULL ENABLE);
  ALTER TABLE "FTPGETWORK"."FTP_WORKER_INSTANCE" MODIFY ("NAZWA" NOT NULL ENABLE);
  ALTER TABLE "FTPGETWORK"."FTP_WORKER_INSTANCE" MODIFY ("FUNKCJA" NOT NULL ENABLE);
  ALTER TABLE "FTPGETWORK"."FTP_WORKER_INSTANCE" MODIFY ("KTO_ODPOWIADA" NOT NULL ENABLE);
  ALTER TABLE "FTPGETWORK"."FTP_WORKER_INSTANCE" MODIFY ("EMAIL2ADM" NOT NULL ENABLE);
  ALTER TABLE "FTPGETWORK"."FTP_WORKER_INSTANCE" ADD CONSTRAINT "PK_FTP_WORKER_INSTANCE" PRIMARY KEY ("XX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  DDL for Trigger BI_FTP_WORKER_INSTANCE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "FTPGETWORK"."BI_FTP_WORKER_INSTANCE" before insert on ftp_worker_instance
for each row begin
  if :new.xx is null then
    select ftp_worker_instance_xx.nextval into :new.xx from dual;
  end if;
end;
/
ALTER TRIGGER "FTPGETWORK"."BI_FTP_WORKER_INSTANCE" ENABLE;
