--------------------------------------------------------
--  File created - pi¹tek-kwietnia-17-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FTP_SCHEDULE
--------------------------------------------------------

  CREATE TABLE "FTPGETWORK"."FTP_SCHEDULE" 
   (	"XX" NUMBER, 
	"END_XX" NUMBER, 
	"NAZWA" VARCHAR2(128 BYTE), 
	"JOB_START" NUMBER, 
	"JOB_STOP" NUMBER, 
	"JOB_STEP" NUMBER, 
	"DISABLED" NUMBER(1,0), 
	"USUNIETY" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "FTPGETWORK"."FTP_SCHEDULE"."JOB_START" IS 'ilosc minut od poczatku tygodnia';
   COMMENT ON COLUMN "FTPGETWORK"."FTP_SCHEDULE"."JOB_STOP" IS 'ilosc minut od poczatku tygodnia';
   COMMENT ON COLUMN "FTPGETWORK"."FTP_SCHEDULE"."JOB_STEP" IS 'co ile minut powtarza?';
--------------------------------------------------------
--  DDL for Index PK_FTP_SCHEDULE
--------------------------------------------------------

  CREATE UNIQUE INDEX "FTPGETWORK"."PK_FTP_SCHEDULE" ON "FTPGETWORK"."FTP_SCHEDULE" ("XX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table FTP_SCHEDULE
--------------------------------------------------------

  ALTER TABLE "FTPGETWORK"."FTP_SCHEDULE" MODIFY ("XX" NOT NULL ENABLE);
  ALTER TABLE "FTPGETWORK"."FTP_SCHEDULE" MODIFY ("END_XX" NOT NULL ENABLE);
  ALTER TABLE "FTPGETWORK"."FTP_SCHEDULE" MODIFY ("NAZWA" NOT NULL ENABLE);
  ALTER TABLE "FTPGETWORK"."FTP_SCHEDULE" MODIFY ("JOB_START" NOT NULL ENABLE);
  ALTER TABLE "FTPGETWORK"."FTP_SCHEDULE" MODIFY ("JOB_STOP" NOT NULL ENABLE);
  ALTER TABLE "FTPGETWORK"."FTP_SCHEDULE" MODIFY ("JOB_STEP" NOT NULL ENABLE);
  ALTER TABLE "FTPGETWORK"."FTP_SCHEDULE" ADD CONSTRAINT "PK_FTP_SCHEDULE" PRIMARY KEY ("XX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "FTPGETWORK"."FTP_SCHEDULE" ADD CONSTRAINT "CK_SCHED_IN_WEEK" CHECK (0<=job_start and job_stop<10080) DISABLE;
--------------------------------------------------------
--  Ref Constraints for Table FTP_SCHEDULE
--------------------------------------------------------

  ALTER TABLE "FTPGETWORK"."FTP_SCHEDULE" ADD CONSTRAINT "FK_SCHEDULE_ENDPOINT" FOREIGN KEY ("END_XX")
	  REFERENCES "FTPGETWORK"."FTP_ENDPOINT" ("XX") ENABLE;
--------------------------------------------------------
--  DDL for Trigger BI_FTP_SCHEDULE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "FTPGETWORK"."BI_FTP_SCHEDULE" before insert on ftp_schedule
for each row begin
  if :new.xx is null then
    select ftp_schedule_xx.nextval into :new.xx from dual;
  end if;
end;


/
ALTER TRIGGER "FTPGETWORK"."BI_FTP_SCHEDULE" ENABLE;
