--------------------------------------------------------
--  File created - niedziela-maja-17-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FTP_ENDPOINT
--------------------------------------------------------

  CREATE TABLE "FTPGETWORK"."FTP_ENDPOINT" 
   (	"XX" NUMBER, 
	"INS_XX" NUMBER, 
	"HOST" VARCHAR2(64 BYTE), 
	"USERID" VARCHAR2(32 BYTE), 
	"PASSWD" VARCHAR2(32 BYTE), 
	"REMOTE_DIR" VARCHAR2(256 BYTE), 
	"LOCAL_DIR" VARCHAR2(256 BYTE), 
	"REFRESH_DATE" DATE DEFAULT sysdate, 
	"PROTOCOL" NUMBER(1,0), 
	"DIRECTION" NUMBER(1,0), 
	"TRANSFER_MODE" NUMBER(1,0), 
	"USUNIETY" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_FTP_ENDPOINT
--------------------------------------------------------

  CREATE UNIQUE INDEX "FTPGETWORK"."PK_FTP_ENDPOINT" ON "FTPGETWORK"."FTP_ENDPOINT" ("XX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table FTP_ENDPOINT
--------------------------------------------------------

  ALTER TABLE "FTPGETWORK"."FTP_ENDPOINT" MODIFY ("XX" NOT NULL ENABLE);
  ALTER TABLE "FTPGETWORK"."FTP_ENDPOINT" MODIFY ("INS_XX" NOT NULL ENABLE);
  ALTER TABLE "FTPGETWORK"."FTP_ENDPOINT" MODIFY ("HOST" NOT NULL ENABLE);
  ALTER TABLE "FTPGETWORK"."FTP_ENDPOINT" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "FTPGETWORK"."FTP_ENDPOINT" MODIFY ("PASSWD" NOT NULL ENABLE);
  ALTER TABLE "FTPGETWORK"."FTP_ENDPOINT" MODIFY ("REMOTE_DIR" NOT NULL ENABLE);
  ALTER TABLE "FTPGETWORK"."FTP_ENDPOINT" MODIFY ("LOCAL_DIR" NOT NULL ENABLE);
  ALTER TABLE "FTPGETWORK"."FTP_ENDPOINT" MODIFY ("REFRESH_DATE" NOT NULL ENABLE);
  ALTER TABLE "FTPGETWORK"."FTP_ENDPOINT" ADD CONSTRAINT "PK_FTP_ENDPOINT" PRIMARY KEY ("XX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "FTPGETWORK"."FTP_ENDPOINT" ADD CONSTRAINT "CK_MODE" CHECK (transfer_mode in (1,2)) ENABLE;
  ALTER TABLE "FTPGETWORK"."FTP_ENDPOINT" MODIFY ("PROTOCOL" NOT NULL ENABLE);
  ALTER TABLE "FTPGETWORK"."FTP_ENDPOINT" MODIFY ("DIRECTION" NOT NULL ENABLE);
  ALTER TABLE "FTPGETWORK"."FTP_ENDPOINT" MODIFY ("TRANSFER_MODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table FTP_ENDPOINT
--------------------------------------------------------

  ALTER TABLE "FTPGETWORK"."FTP_ENDPOINT" ADD CONSTRAINT "FK_ENDPOINT_INST" FOREIGN KEY ("INS_XX")
	  REFERENCES "FTPGETWORK"."FTP_WORKER_INSTANCE" ("XX") ENABLE;
--------------------------------------------------------
--  DDL for Trigger BI_FTP_ENDPOINT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "FTPGETWORK"."BI_FTP_ENDPOINT" before insert on ftp_endpoint
for each row begin
  if :new.xx is null then
    select ftp_endpoint_xx.nextval into :new.xx from dual;
  end if;
end;


/
ALTER TRIGGER "FTPGETWORK"."BI_FTP_ENDPOINT" ENABLE;
